---
# Tasks for qpid role

- name: install base packages for qpid
  yum: name={{ item }} state=installed
  with_items: 
   - qpid-cpp-client
   - qpid-cpp-server

- name: activate qpid service
  service: name={{ item }} state=started enabled=yes
  with_items:
   - qpidd 