---
# Tasks for openstack neutron l3 agent

- name: install keystone client
  yum: name=python-keystoneclient 

# RDO and RHOS to be re-packaged with more granularity
- name: install neutron
  yum: name=openstack-neutron state=present

- include: ovs-external-bridge.yml

- name: configure l3 agent 
  command: /usr/bin/openstack-config --set /etc/neutron/l3_agent.ini DEFAULT {{ item }}
  with_items:
    - debug False
    - verbose True
    - interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
    - ovs_use_veth True
    - use_namespaces True
    - external_network_bridge br-ex
    # - router_id <id>
    # - gateway_external_network_id <id>

- name: activate l3 agent
  service: name=neutron-l3-agent state=started enabled=yes
