---
# Tasks for openstack networking dhcp agent

# RDO and RHOS to re-packaged for better granularity
- name: install neutron
  yum: name=openstack-neutron

- name: configure neutron 
  command: /usr/bin/openstack-config --set /etc/neutron/neutron.conf DEFAULT {{ item }}
  with_items:
    - core_plugin neutron.plugins.openvswitch.ovs_neutron_plugin.OVSneutronPluginV2
    - control_exchange neutron
    - qpid_hostname {{ controller_ip }}
    - rpc_backend neutron.openstack.common.rpc.impl_qpid
    - notification_topics notifications

- name: allow overlapping subnets
  command: /usr/bin/openstack-config --set /etc/neutron/neutron.conf DEFAULT allow_overlapping_ips True

- name: configure common device manager options
  command: /usr/bin/openstack-config --set /etc/neutron/dhcp_agent.ini DEFAULT {{ item }}
  with_items:
    - interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
    - auth_url http://{{ controller_ip }}:35357/v2.0/
    - admin_tenant_name service
    - admin_username neutron
    - admin_password {{ neutron_service_pass }}
    - ovs_use_veth True
    - debug False
    - verbose True

- name: configure dhcp agent
  command: /usr/bin/openstack-config --set /etc/neutron/dhcp_agent.ini DEFAULT {{ item }}
  with_items:
  - dhcp_driver neutron.agent.linux.dhcp.Dnsmasq
  - root_helper "sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf"
  - use_namespaces True

- name: activate dhcp agent
  service: name=neutron-dhcp-agent state=started enabled=yes
