---
# Tasks for openstack neutron service node

# Agent package required for configuration (see handlers)
- name: install neutron server
  yum: name={{ item }} state=present
  with_items:
    - openstack-quantum
    - openstack-quantum-openvswitch
    - openstack-utils

- name: setup neutron database
  shell: /usr/bin/quantum-server-setup -q {{ quantum_db_pass }} -u quantum -r "{{ mysql_root_pass }}" --plugin openvswitch -y
         creates=/var/lib/mysql/ovs_quantum

- name: grant quantum user from local IP
  mysql_user: name=quantum password={{ quantum_db_pass }}
              host={{ controller_fqdn }}
              priv=ovs_quantum.*:ALL
              state=present

- name: add service tenant
  keystone_user: token={{ keystone_admin_token }} endpoint="http://localhost:35357/v2.0/" tenant=service tenant_description="Service Tenant" 

- name: add neutron user for service tenant
  keystone_user: token={{ keystone_admin_token }} endpoint="http://localhost:35357/v2.0/" user=quantum tenant=service password={{ quantum_pass }}

- name: add neutron user role for service tenant
  keystone_user: token={{ keystone_admin_token }} endpoint="http://localhost:35357/v2.0/" role=admin user=quantum tenant=service

- name: copy keystonerc file for service tenant
  template: src=keystonerc.j2 dest=/root/keystonerc_service mode=0755

- include: nova-config.yml

- name: restart nova on controller
  service: name={{ item }} state=restarted 
  with_items:
   - openstack-nova-api
   - openstack-nova-scheduler
   - openstack-nova-cert
   - openstack-nova-console
   - openstack-nova-conductor
  delegate_to: "{{ controller_ip }}"

- include: ../../openstack-neutron-l2-agent/tasks/plugin-config.yml

- name: activate quantum service
  service: name=quantum-server state=started enabled=yes
