---
# Tasks for openstack neutron service (neutron-server)

# Agent package required for configuration (see handlers)
- name: install neutron server
  yum: name={{ item }} state=present
  with_items:
    - openstack-neutron
    - openstack-neutron-openvswitch
    - openstack-utils

- name: create ovs_neutron database
  mysql_db: name=ovs_neutron state=present

- name: grant sql neutron user from %
  mysql_user: name=neutron password={{ neutron_db_pass }} host=%
              priv=ovs_neutron.*:ALL state=present

- name: grant sql neutron user from local IP
  mysql_user: name=neutron password={{ neutron_db_pass }} host={{ controller_private_fqdn }}
              priv=ovs_neutron.*:ALL state=present

- name: grant sql neutron user from localhost
  mysql_user: name=neutron password={{ neutron_db_pass }} host=localhost
              priv=ovs_neutron.*:ALL state=present

- include: nova-config.yml

- name: restart nova on controller
  service: name={{ item }} state=restarted 
  with_items:
   - openstack-nova-api
   - openstack-nova-scheduler
   - openstack-nova-cert
   - openstack-nova-console
   - openstack-nova-conductor
  delegate_to: "{{ controller_private_ip }}"

- include: ../../openstack-neutron-l2-agent/tasks/plugin-config.yml

- name: activate neutron service
  service: name=neutron-server state=started enabled=yes
