---
# Tasks for the glance controller node

- name: Install glance OpenStack  components
  yum: name=openstack-glance state=installed

# Workaround for BZ# 997290 on RHOS
- name: copy default glance-registry-paste.ini
  command: /bin/cp /usr/share/glance/glance-registry-dist-paste.ini /etc/glance/glance-registry-paste.ini
           creates=/etc/glance/glance-registry-paste.ini

- name: copy default glance-api-paste.ini 
  command: /bin/cp /usr/share/glance/glance-api-dist-paste.ini /etc/glance/glance-api-paste.ini
           creates=/etc/glance/glance-api-paste.ini
# End workaround

- name: Copy configuration files for glance
  template: src=glance-api.conf.j2 dest=/etc/glance/glance-api.conf
  notify: restart glance

- name: Copy configuration files for glance
  template: src=glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf
  notify: restart glance

- name: fix glance config files ownershipd
  file: path=/etc/glance recurse=yes owner=root group=glance state=directory 

- name: Setup DB for glance
  shell: creates=/var/lib/mysql/glance /usr/bin/openstack-db --init --service glance -p {{ glance_db_pass }} -r "{{ mysql_root_pass }}" -y

- name: DB sync for Glance
  shell: /usr/bin/glance-manage db_sync; touch /etc/glance/db.synced
         creates=/etc/glance/db.synced

- name: start the glance services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - openstack-glance-api
   - openstack-glance-registry

