---
# Tasks for the Horizon controller node

- name: install OpenStack Horizon packages
  yum: name={{ item }} state=installed
  with_items: 
   - memcached 
   - python-memcached 
   - mod_wsgi 
   - openstack-dashboard
   - openstack-nova-novncproxy

- name: copy horizon configuration file
  template: src=local_settings.j2 dest=/etc/openstack-dashboard/local_settings
  notify: restart horizon

- name: activate horizon services
  service: name={{ item }} state=started enabled=yes
  with_items:
   - openstack-nova-consoleauth
   - openstack-nova-novncproxy
   - httpd
   - memcached


