---
# Tasks for the keystone controller node

- name: Install OpenStack keystone  packages.
  yum: name={{ item }} state=installed
  with_items: 
   - openstack-keystone
   - python-keystoneclient

- name: Setup DB for keystone
  shell: creates=/var/lib/mysql/keystone /usr/bin/openstack-db --init --service keystone -p {{ keystone_db_pass }} -r "{{ mysql_root_pass }}" -y 

# keystone.conf
- name: configure keystone [DEFAULT] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf DEFAULT admin_token {{ keystone_admin_token }}

- name: configure keystone [sql] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf sql connection mysql://keystone:{{ keystone_db_pass }}@localhost/keystone

- name: configure keystone [identity] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf identity driver keystone.identity.backends.sql.Identity

- name: configure keystone [catalog] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf catalog {{ item }}
  with_items:
    - template_file /etc/keystone/default_catalog.templates
    - driver keystone.catalog.backends.sql.Catalog

- name: configure keystone [token] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf token driver keystone.token.backends.sql.Token

- name: configure keystone [ec2] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf ec2 driver keystone.contrib.ec2.backends.sql.Ec2

- name: configure keystone [auth] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf auth {{ item }}
  with_items:
    - methods external,password,token
    - password keystone.auth.plugins.password.Password
    - token keystone.auth.plugins.token.Token

- name: configure keystone [paste_deploy] section
  command: /usr/bin/openstack-config --set /etc/keystone/keystone.conf paste_deploy config_file keystone-paste.ini
# End of keystone.conf

- name: Create certs for the keystone
  shell: creates=/etc/keystone/ssl/certs/ca.pem
         /usr/bin/keystone-manage pki_setup  --keystone-user keystone --keystone-group keystone; chmod 777 /var/lock

# Might be obsolete
#- name: Change ownership of all files to keystone
#  file: path=/etc/keystone recurse=yes owner=keystone group=keystone state=directory

# Migration
- name: copy keystone mysql data
  copy: src=keystone.mysql dest=/root/keystone-import.mysql
  when: migrate

- name: inject keystone mysql data
  shell: /usr/bin/mysql -u root keystone < /root/keystone-import.mysql
  when: migrate
# End Migration

- name: DB sync for keystone
  shell: /usr/bin/keystone-manage db_sync; touch /etc/keystone/db.synced
         creates=/etc/keystone/db.synced

# Under Fedora, starting service migth timeout: ignore it
- name: start keystone service
  service: name=openstack-keystone state=started enabled=yes
  ignore_errors: True

- name: copy script keystone initialization
  template: src=keystone_data.sh.j2 dest=/tmp/keystone_data.sh mode=0755

- name: create admin keystonerc file
  template: src=keystonerc.j2 dest=/root/keystonerc mode=0755

- name: init keystone database
  shell: creates=/etc/keystone/db.updated /tmp/keystone_data.sh; touch /etc/keystone/db.updated
