---
# Tasks for openstack neutron l2 agent service

# openstack-quantum rpm required as well
- name: install neutron l2 agent
  yum: name={{ item }} state=present
  with_items:
    - openstack-quantum
    - openstack-quantum-openvswitch

- include: plugin-config.yml

- name: activate neutron l2 agent
  service: name={{ item }} state=restarted
  with_items:
    - quantum-openvswitch-agent
    - quantum-ovs-cleanup

- include: ovs-integration-bridge.yml

- include: ovs-internal-bridge.yml

- name: restart l2 agent
  service: name=quantum-openvswitch-agent state=restarted
