---
# Task for openstack networking metadata agent
# RDO and RHOS to be re-packaged for better granularity
- name: install neutron
  yum: name=openstack-neutron

- name: configure metadata agent  
  command: /usr/bin/openstack-config --set /etc/neutron/metadata_agent.ini DEFAULT {{ item }}
  with_items:
    - nova_metadata_ip {{ controller_ip }}
    - admin_user neutron
    - admin_password {{ neutron_service_pass }}
    - admin_tenant_name service
    - auth_url http://{{ controller_ip }}:35357/v2.0/
    - metadata_proxy_shared_secret {{ neutron_metadata_proxy_shared_secret }}

- name: configure nova for openstack networking metadata agent
  command: /usr/bin/openstack-config --set /etc/nova/nova.conf DEFAULT {{ item }}
  with_items:
    - service_neutron_metadata_proxy True
    - neutron_metadata_proxy_shared_secret {{ neutron_metadata_proxy_shared_secret }}
  delegate_to: "{{ controller_ip }}"

- name: activate metadata agent
  service: name=neutron-metadata-agent state=started enabled=yes