---
# Tasks for the openstack virt compute nodes

- name: Install the required virtualization packages
  yum: name={{ item }} state=installed
  with_items:
   - qemu-img
   - qemu-kvm
   - qemu-kvm-tools
   - libvirt
   - libvirt-client
   - libvirt-python
   - libguestfs-tools

- name: Configure qemu.conf in libvirt
  copy: src=qemu.conf.j2 dest=/etc/libvirt/qemu.conf

- name: service libvirt start
  service: name=libvirtd state=started enabled=yes

- name: Stop libvirt default network
  command: /usr/bin/virsh net-destroy default 
  ignore_errors: True

- name: Delete libvirt default network
  command: /usr/bin/virsh net-undefine default  
  ignore_errors: True

- name: create link for the qemu
  file: src=/usr/libexec/qemu-kvm dest=/usr/bin/qemu-system-x86_64 state=link
  when: ansible_distribution == 'RedHat'

